### ISSUE TITLE
Correction in build.sbt 

### ISSUE THREAD

**Issue by moises-trelles** [holdenk/sparkProjectTemplate.g8#3]
Hi Holden, 

I had a little problem when i tried to import the genered projet in intellij.
In the  file sparkProjectTemplate.g8/src/main/g8/build.sbt (libraryDependencies  part) there is a parenthesis in a wrong position.

Original
libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % "3.0.1" % "test",
      "org.scalacheck" %% "scalacheck" % "1.13.4" % "test",
      "com.holdenkarau" %% "spark-testing-base" ) <== here   % "2.2.0_0.7.1" % "test", 

Correction:

libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % "3.0.1" % "test",
      "org.scalacheck" %% "scalacheck" % "1.13.4" % "test",
      "com.holdenkarau" %% "spark-testing-base" % "2.2.0_0.7.1" % "test"),  <== here

Let me now if  my commentary/correction is correct. 
I try this and  that works for me when i make an import from Intellij.

Thank you very much for your Template :)

**Comment by ericksepulveda** [comment]
hit the same issue, PR at https://github.com/holdenk/sparkProjectTemplate.g8/pull/4
